Capstone project for module1
herokudev/Movie-premier pull request #1
Opened 2021-08-11 22:48 UTC by herokudev

HTML/CSS & JavaScript capstone project

For this capstone project a take the Conference website as a reference but change the subject to a World Movie Premier

Yesterday we have GitHub problems and could not create the desktop-design branch until today.

2021-08-12 01:57 UTC, rloterh requested changes
Hi Herbert, 

You did extremely great on this project!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Good Points 👍  
- App correctly deployed to GitHub pages
- No linter errors


## Required Changes ♻️
- [ ] _Kindly check the comments under the review._


Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 4 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 01:57 UTC, rloterh commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
- [ ] Your application does not include the `Partners` section and the `Footer section` for both mobile and desktop versions on the `index` and `about` pages.
- [ ] Your application is overlapping for both desktop and mobile versions on the `index` and `about` pages.
- [ ] The images in the `Featured Actors` section of  your design is missing the background decoration

**Your desktop design (bottom part of page):**
![image](https://user-images.githubusercontent.com/12745474/129123056-cf8c5fd9-3ff3-4a59-82ee-6f7e11cfb490.png)

**Your mobile design (bottom part of page):**
![image](https://user-images.githubusercontent.com/12745474/129123181-159b86aa-3d00-4f2b-a571-5ea993c6a7e8.png)

**The original desktop design (bottom part of page):**
![image](https://user-images.githubusercontent.com/12745474/129123398-d915739c-ed49-4d4d-a947-5ba97e2fc207.png)

**The original mobile design (bottom part of page):**
![image](https://user-images.githubusercontent.com/12745474/129123560-a0b06576-d502-4c79-bcdc-b7cd43bc3d4b.png)

2021-08-12 01:57 UTC, rloterh commented on index.html
> +                    <a href="#mobileMain" class="nav-link">Main Program</a>
- [ ] The middle section of the mobile design  does not have spacing between the items. Kindly ensure to improve upon this aspect.

**Your design:**

![image](https://user-images.githubusercontent.com/12745474/129125240-e2a19b3c-503a-4da9-88c6-6ede8bb6853a.png)

**The original design**
![image](https://user-images.githubusercontent.com/12745474/129125339-7fa3231e-365f-44aa-b785-a93208ecf489.png)

2021-08-12 01:57 UTC, rloterh commented on index.html
> +            BLACK WIDOW MOVIE PREMIER 2021
- [ ] To enhance proper HTML semantics kindly ensure that there's at least 1, but no more than 1, `h1` tag in each page
- [ ] To make our design look closely as much as possible to the provided [design template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) let's ensure to use appropriate `fonts`, `font weights` and `font sizes`.

2021-08-12 20:00 UTC, herokudev commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
The describing video is done: 
Here is the link:
https://www.loom.com/share/ee732abfcc1d41d084389dd40a40929c

2021-08-12 20:00 UTC, herokudev commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
Acknowledge section added

2021-08-12 20:02 UTC, herokudev commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
Background decoration added, also footer for both pages.

2021-08-12 22:54 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @herokudev , 

Great work on making the changes requested by a previous reviewer 👏 
You have a video presentation of the project now :clap: 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply **missed by the previous reviewer** and addressing them will really improve your application._

Happy Hacking! :computer: 

-----

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 22:54 UTC, sinansevgi commented on index.html
> +                    <a href="#mobileMain" class="nav-link">Main Program</a>
- [ ] This section still missing proper design. You can personalize the content (text. images) but you should follow the given design template. This is one of the key requirements of this project. Please update this section with proper design and placing.

2021-08-12 22:54 UTC, sinansevgi commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
- [ ] Please add the video link to the pull request description so other code reviewers can also notice it easily.

2021-08-12 22:54 UTC, sinansevgi commented on index.html
>              </div>
[Optional]

- [ ]  One of the key requirements for this project is generating this section dynamically with javascript. You should create a javascript object that keeps the information about speakers and create a function that generates HTML elements from this object. Looks like the previous code reviewer missed this so I am marking this as optional but highly recommending you to make this change.

2021-08-12 22:54 UTC, sinansevgi commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
- [ ] The page still has a massive overflow to right and it looks really bad. This issue also affecting the responsiveness of the page. You can try to use the grid or flex to place elements on the page instead of giving static sizes to elements.

![Screenshot 2021-08-13 at 00-57-44 World Premiere Fan Event](https://user-images.githubusercontent.com/1642014/129276840-e2f540eb-56b1-4cd3-b0dc-59ce699d2d9a.png)

2021-08-12 22:54 UTC, sinansevgi commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
- [ ] Newly added `Partners` and the `Footer` sections have left margin that doesn't exist on the original design. Please remove this margin.
![Screenshot 2021-08-13 at 01-31-06 World Premiere Fan Event](https://user-images.githubusercontent.com/1642014/129278214-3b46210b-e450-4d0f-9d52-0f7958ca8144.png)

2021-08-13 01:08 UTC, herokudev commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
Top menu, partners and footer sections now have width 100%, eliminating margin and overflow.

2021-08-13 02:27 UTC, herokudev commented on index.html
> +                    <a href="#mobileMain" class="nav-link">Main Program</a>
New design for the section is done.

2021-08-13 04:07 UTC, rloterh requested changes
Hi Paka and Yannick-Noel, 

You did great on this project, and for making the changes requested by the previous reviewer(s)!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚥 

## Good Points 👍  
- No linter errors

## Required Changes ♻️
- [ ] _Kindy check the comments above, made under the reviews of the previous code reviewer(s) and stating **not properly resolved**. Kindly take your time to correctly review those issues outlined by the previous code reviewers, and please check to see that the changes are working as intended._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider the comments marked [OPTIONAL] under this review:



Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 04:07 UTC, rloterh commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
This issue is well resolved! ✔️

2021-08-13 04:07 UTC, rloterh commented on index.html
>              <img id="closeIcon" class="nav-item2" src="images/close-window-24.png" alt="close button">
- [ ] As informed by the previous code reviewer, overlapping issue still exist, although you have hidden the overflow portions, Kindly ensure to improve upon this aspect.

**Your design(mobile view):**
![image](https://user-images.githubusercontent.com/12745474/129303304-5e20ac1e-6635-4868-bdf8-7f424ef12fb4.png)

2021-08-13 17:50 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @herokudev 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
Changes required :writing_hand:  
 
 * #### Please check the comments under the review too
     
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-13 17:50 UTC, Emmyn5600 commented on index.html
>              </div>
- [ ] This not yet solved, I highly recommend you to work on it as suggested by the previous reviewer, what you have to do is to use a function to generate HTML elements as well as images from the object.

The section "Featured speakers" is generated dynamically with JavaScript.
The JavaScript code is within it's own .js file, not inside the HTML in script tags.
The list of speakers used to generate the HTML is assigned to a variable as an array or object.
The list of speakers contain an speaker object for each that holds their specific data.

Example:

{
  name: "Julia Leda", 
  role: "President of Young pirates of Europe", 
  description: "European ingetration, political democracy, and participation of ...", 
  photo: "image_url_here"
}

2021-08-13 17:50 UTC, Emmyn5600 commented on index.html
> +                    <a href="#mobileMain" class="nav-link">Main Program</a>
- [ ] This is not yet solved, please work on it as suggested by the previous reviewer.

2021-08-14 05:07 UTC, SpaYco reviewed
Hello 👋,

This is an additional review as a result of the second opinion request.

what the Code Reviewer meant here is to add some description on each card

|Yours|Original|
|--|--|
| ![image](https://user-images.githubusercontent.com/11758151/129434709-e13c818c-d34d-4a5a-b0ca-96b104d7ba33.png) | ![image](https://user-images.githubusercontent.com/11758151/129434775-a80e66f7-23d2-48f9-b69d-72aad66c1218.png) |

do this change and your project should be approved afterwards, also please do the optional ones as they are super important :)

Keep rocking 🚀!

2021-08-15 01:21 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Herbert, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer(s). There is nothing else to say other than... it's time to merge it 🍾 🍾 :shipit: .
Congratulations! 🎉 🎉 🌟 


<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have no more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-15 02:03 UTC, merged